services:
  app:
    build:
      context: .       # Set context to current directory (project root)
      dockerfile: Dockerfile
    container_name: openagent-service
    ports:
      - "${PORT:-8800}:${PORT:-8800}"
    volumes:
      - ./data:/app/data # Map host's ./data directory to container's /app/data
      - ./static:/app/static # Map static assets
      - ./tpl:/app/tpl # Map template files
      - ./migrations:/app/migrations # Map migrations directory
    env_file:
      - .env # Path relative to compose file (now in same directory)
    environment:
      - PORT=${PORT:-8800}
      - DATA_DIR=/app/data
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - SYSADMIN_EMAIL=${SYSADMIN_EMAIL}
      - APP_NAME=${APP_NAME:-OpenAgent}
      - APP_VERSION=${APP_VERSION:-1.0.0}
    depends_on:
      - postgres
    networks:
      - app-net
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: postgres-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data: # Persist PostgreSQL data
