version: '3.8'

services:
  app-server:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: openagent-service
    ports:
      - "8800:8800" # Map host port 8800 to container port 8800
    volumes:
      - ./data:/app/data # Map host's ./data directory to container's /app/data
      - ./static:/app/static # Map static assets
      - ./tpl:/app/tpl # Map template files
    environment:
      # --- Application Settings ---
      PORT: 8800
      DATA_DIR: /app/data
      # --- PostgreSQL Connection (Optional) ---
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: agentdb
      # --- Email Settings ---
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: your-email@example.com
      SMTP_PASSWORD: your-email-password
      SMTP_FROM: noreply@example.com
    depends_on:
      - postgres
    networks:
      - app-net
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: postgres-service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agentdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net
    restart: unless-stopped

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data: # Persist PostgreSQL data
