version: '3.8'

services:
  go-agent:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: go-agent-service
    ports:
      - "8800:8800" # Map host port 8800 to container port 8800
    volumes:
      - ./data:/app/data # Map host's ./data directory to container's /app/data
    environment:
      # --- Ollama Connection ---
      # Connect to the ollama service on the same Docker network
      OLLAMA_URL: http://ollama:11434
      # --- Other Settings ---
      OLLAMA_MODEL: mistral:7b # Smaller model than llama3:8b
      PORT: 8800             # Optional: Override agent's listening port
    depends_on:
      - ollama
    networks:
      - agent-net
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - agent-net
    restart: unless-stopped

networks:
  agent-net:
    driver: bridge

volumes:
  ollama_data: # Persist Ollama models and data
